In [1]:
import numpy as np

# Array

In [2]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [3]:
np.array(['a', 'b', 'c', 'd', 1, 2, 3, 4, 5, 6.5, 7.2, 8.4])

array(['a', 'b', 'c', 'd', '1', '2', '3', '4', '5', '6.5', '7.2', '8.4'],
      dtype='<U3')

In [4]:
np.array([1, 2, 3, 4, 5, 6], dtype=float)

array([1., 2., 3., 4., 5., 6.])

In [6]:
np.array([1, 2, 3, 4, 5, 6], ndmin=10)

array([[[[[[[[[[1, 2, 3, 4, 5, 6]]]]]]]]]])

In [7]:
type(np.array([1, 2, 3, 4, 5, 6], ndmin=10))

numpy.ndarray

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6], ndmin=10)

In [9]:
arr.ndim

10

In [10]:
l = [1, 2, 3, 4, 5, 6]
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [11]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [12]:
arr.argmin()

0

In [14]:
arr.dtype

dtype('int32')

In [17]:
arr = np.arange(0, 100)

In [25]:
a = arr.reshape(20, 5)

In [26]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
arr.resize(10, 10)

In [29]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# from function

In [30]:
np.fromfunction(lambda i, j: i*j, (4, 4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [42]:
example = lambda i, j: i*j

In [40]:
def example2(i, j):
    return i*j

In [44]:
example(10, 20)

200

In [41]:
example2(10, 29)

290

In [50]:
np.fromfunction(lambda i, j: i==j, (2, 2))

array([[ True, False],
       [False,  True]])

In [53]:
tuple((x for x in range(10)))

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [60]:
i = (x for x in range(10))

In [56]:
for j in i:
    print(j)

0
1
2
3
4
5
6
7
8
9


In [61]:
np.fromiter(i, int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.fromstring("10,20,30,40,50", sep=',', dtype=int)

array([10, 20, 30, 40, 50])

# zeros and ones

In [64]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [66]:
np.zeros(100)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [67]:
np.ones(100)+5

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [72]:
np.linspace(1, 5, 7)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [73]:
np.ones((5, 3, 8))+10

array([[[11., 11., 11., 11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11., 11., 11., 11.]],

       [[11., 11., 11., 11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11., 11., 11., 11.]],

       [[11., 11., 11., 11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11., 11., 11., 11.]],

       [[11., 11., 11., 11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11., 11., 11., 11.]],

       [[11., 11., 11., 11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11., 11., 11., 11.]]])

# random

In [76]:
np.random.rand(2, 3)

array([[0.25200062, 0.52005941, 0.26774146],
       [0.9840992 , 0.76466472, 0.94857507]])

In [77]:
np.random.randn(4, 3)

array([[ 0.44431995,  0.40688545,  1.42583806],
       [-0.76423548, -1.36021435, -0.49366378],
       [-0.19492405, -2.05599073, -0.0052709 ],
       [-0.17808769,  1.56454574,  2.54701733]])

In [100]:
np.random.randint(10, 100)

43

In [101]:
np.random.randint(10, 100, (10, 10))

array([[24, 66, 39, 86, 89, 25, 48, 81, 30, 29],
       [16, 28, 71, 37, 70, 75, 65, 71, 46, 47],
       [44, 25, 79, 64, 29, 24, 99, 59, 38, 68],
       [32, 80, 21, 20, 75, 35, 56, 85, 66, 61],
       [36, 87, 14, 76, 97, 56, 37, 31, 76, 97],
       [53, 45, 47, 41, 93, 99, 19, 96, 25, 16],
       [47, 14, 69, 76, 17, 95, 43, 96, 47, 63],
       [86, 95, 17, 71, 76, 46, 10, 72, 16, 61],
       [51, 35, 96, 31, 73, 78, 93, 21, 95, 78],
       [42, 64, 24, 84, 48, 50, 17, 73, 33, 58]])

# statical and math numpy

In [102]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [103]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [104]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

In [105]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619])

In [106]:
np.pi

3.141592653589793

In [107]:
np.sin(arr*np.pi/180)

array([0.01745241, 0.0348995 , 0.05233596, 0.06975647, 0.08715574,
       0.10452846])

In [108]:
np.degrees(arr)

array([ 57.29577951, 114.59155903, 171.88733854, 229.18311805,
       286.47889757, 343.77467708])

In [111]:
arr2 = np.array(np.random.randint(10, 100, 20))

In [112]:
arr2

array([89, 78, 50, 37, 26, 20, 56, 99, 40, 48, 92, 79, 33, 36, 71, 52, 81,
       94, 15, 89])

In [113]:
np.min(arr2)

15

In [114]:
np.max(arr2)

99

In [115]:
np.ptp(arr2)

84

In [117]:
arr2.reshape(4, 5)

array([[89, 78, 50, 37, 26],
       [20, 56, 99, 40, 48],
       [92, 79, 33, 36, 71],
       [52, 81, 94, 15, 89]])

In [118]:
np.ptp(arr2.reshape(4, 5), axis=1)

array([63, 79, 59, 79])

In [119]:
np.ptp(arr2.reshape(4, 5), axis=0)

array([72, 25, 66, 25, 63])

In [122]:
np.percentile(arr2.reshape(4, 5), 25, axis=1)

array([37., 40., 36., 52.])

In [123]:
np.mean(arr2)

59.25

In [124]:
np.median(arr2)

54.0

In [125]:
np.sort(arr2)

array([15, 20, 26, 33, 36, 37, 40, 48, 50, 52, 56, 71, 78, 79, 81, 89, 89,
       92, 94, 99])

In [126]:
np.average(arr2)

59.25

In [127]:
np.std(arr2)

26.417560447550795

In [128]:
np.var(arr2)

697.8875

In [129]:
np.sqrt(697.8875)

26.417560447550795